"""
Django settings for search_association project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os.path
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print(os.path.join(BASE_DIR, "utils"))
sys.path.append(os.path.join(BASE_DIR, "utils"))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+(_#aquprnv&8-i$+vq5(4huw0d*elwm+nqje4a@uup-m7&kft'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['192.168.1.2']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'game',
    'industry',
    'museum'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'search_association.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'search_association.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# 设置APP对应的数据库路由表：不同APP应用对应不同的数据库
DATABASES_APPS_MAPPING = {
    "game": "game_analysis",
    "industry": "industry",
    "museum": "museum"
}
DATABASE_ROUTERS = ['search_association.app_db_router.DatabaseAppsRouter']

DATABASES = {
    # 本地测试用数据库
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
        'NAME': 'GAMEANALYSIS',  # 数据库名
        "HOST": "192.168.1.2",
        "USER": "DEV",
        "PASSWORD": "dev2023",
        "PORT": 3306
    },
    # 游戏论坛数据库
    'game_analysis': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
        'NAME': 'GAMEANALYSIS',  # 数据库名
        "HOST": "192.168.1.2",
        "USER": "DEV",
        "PASSWORD": "dev2023",
        "PORT": 3306
    },
    # 王者荣耀英雄数据库
    'hero_wzry': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
        'NAME': 'hero_test',  # 数据库名
        "HOST": "127.0.0.1",
        "USER": "DEV",
        "PASSWORD": "dev2023",
        "PORT": 3306
    },
    "industry":{
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'industry',
        'USER': 'industry_test_user',
        'PASSWORD': 'test123456',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    "museum":{
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cultural',
        'USER': 'industry_test_user',
        'PASSWORD': 'test123456',
        'HOST': 'localhost',
        'PORT': '5432',
    }

}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
game_name_association_trie = "game_name_association_trie"
